### PR TITLE
Add support for the fit() / fdescribe() syntax

### PR DESCRIPTION
**Pull request by vicb**
To match Jasmine 2.1, see http://pivotallabs.com/new-key-features-
jasmine-2-1/

### CODE REVIEW

**Comment by vsavkin** [comment]
@vicb I am not sure if should have both `iit` and `fit`. It can be confusing. I was planning to replace iit with fit and release guinness 2.0 when it is needed for angular 2.

**Comment by vicb** [comment]
As you prefer. Seems like jasmine support both ?

**Comment by vicb** [comment]
Actually iit / ddescribe seem to be karma additions.

**Comment by vsavkin** [comment]
Yup, iit and ddescribe come from karma.

**Pull request closed without merging**
